services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: supersecret
    networks:
      - internal
    deploy:
      placement:
        constraints:
          - node.role == manager

  server:
    image: ghcr.io/arthurldvd/mfp-server:latest
    environment:
      DB_HOST: db
      DB_PORT: 5432
    networks:
      - internal
      - web
    depends_on:
      - db
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=web"
        - "traefik.http.routers.mfp-api.rule=Host(`api.mfp.local`)"
        - "traefik.http.routers.mfp-api.entrypoints=web"
        - "traefik.http.services.mfp-api.loadbalancer.server.port=3000"

networks:
  internal:
  web:
    external: true
